# Generated by Django 5.1.4 on 2025-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('party', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('photo', models.ImageField(upload_to='candidates/')),
            ],
        ),
    ]
